// Mock data for development — replace with real Supabase queries once connected

export const MOCK_PROJECTS = [
  {
    id: '1',
    name: 'פרויקט רמות - בניין A',
    address: 'רחוב הרצל 12, רמות, ירושלים',
    status: 'active',
    progress: 42,
    contractor: 'ש.ב. בנייה בע"מ',
    stage: 'שלד + קירות חוץ',
    start_date: '2024-09-01',
    end_date: '2025-12-31',
    findings_count: 14,
    open_findings: 7,
    budget: 4200000,
    spent: 1764000,
  },
  {
    id: '2',
    name: 'וילה פרטית - גבעתיים',
    address: 'שדרות הנשיא 5, גבעתיים',
    status: 'active',
    progress: 78,
    contractor: 'מ.א. בנייה',
    stage: 'גמר פנים',
    start_date: '2024-03-15',
    end_date: '2025-09-30',
    findings_count: 6,
    open_findings: 2,
    budget: 1800000,
    spent: 1404000,
  },
  {
    id: '3',
    name: 'מרכז מסחרי - הרצליה',
    address: 'רחוב סוקולוב 44, הרצליה',
    status: 'paused',
    progress: 23,
    contractor: 'גלובל בילד',
    stage: 'יסודות',
    start_date: '2025-01-10',
    end_date: '2026-06-30',
    findings_count: 3,
    open_findings: 3,
    budget: 9500000,
    spent: 2185000,
  },
]

export const MOCK_FINDINGS = [
  {
    id: '1',
    project_id: '1',
    number: 14,
    title: 'פגם בציפוי הרצפה',
    location: 'קומה 3, דירה 8',
    description: 'אריחי רצפה מתנפחים באזור פינת אוכל, ככל הנראה עקב לחות.',
    severity: 'high',
    status: 'open',
    responsible: 'קבלן ריצוף',
    deadline: '2025-08-10',
    standard: 'ת"י 1555',
    created_at: '2025-07-28T09:30:00Z',
    image_url: null,
  },
  {
    id: '2',
    project_id: '1',
    number: 13,
    title: 'סדקים בטיח חיצוני',
    location: 'חזית דרום, קומה 2',
    description: 'סדקי שיער לאורך קו בין קורות לקיר. רוחב < 0.2מ"מ.',
    severity: 'medium',
    status: 'in_review',
    responsible: 'קבלן טיח',
    deadline: '2025-08-05',
    standard: 'ת"י 1627',
    created_at: '2025-07-25T11:00:00Z',
    image_url: null,
  },
  {
    id: '3',
    project_id: '1',
    number: 12,
    title: 'ריווח לא תקני בין מוטות',
    location: 'עמוד P4, קומה 1',
    description: 'מרחק בין מוטות 16 מ"מ = 18 ס"מ, נדרש מקסימום 15 ס"מ לפי תוכנית.',
    severity: 'critical',
    status: 'fixed',
    responsible: 'קבלן ראשי',
    deadline: '2025-07-20',
    standard: 'ת"י 466',
    created_at: '2025-07-18T14:00:00Z',
    image_url: null,
  },
  {
    id: '4',
    project_id: '2',
    number: 6,
    title: 'חלונות לא מיושרים',
    location: 'קומה 2, צד מערב',
    description: 'מסגרות חלונות עם סטייה של 5 מ"מ מהאנך.',
    severity: 'medium',
    status: 'open',
    responsible: 'קבלן אלומיניום',
    deadline: '2025-08-15',
    standard: 'ת"י 1920',
    created_at: '2025-07-22T10:00:00Z',
    image_url: null,
  },
  {
    id: '5',
    project_id: '1',
    number: 11,
    title: 'כיסוי בטון לא מספיק על הברזל',
    location: 'תקרת קומה 2 — אזור חדר מדרגות',
    description: 'כיסוי מינימלי נמדד 15 מ"מ, נדרש מינימום 25 מ"מ לפי ת"י 466.',
    severity: 'critical',
    status: 'open',
    responsible: 'קבלן ראשי',
    deadline: '2025-08-02',
    standard: 'ת"י 466, סעיף 6.3',
    created_at: '2025-07-20T08:00:00Z',
    image_url: null,
  },
  {
    id: '6',
    project_id: '3',
    number: 3,
    title: 'סטייה בקו יסוד',
    location: 'פינה צפון-מזרח',
    description: 'סטייה של 3 ס"מ ביחס לנקודת ייחוס לפי תוכנית מדידה.',
    severity: 'high',
    status: 'open',
    responsible: 'קבלן יסודות',
    deadline: '2025-09-01',
    standard: 'ת"י 1316',
    created_at: '2025-07-15T12:00:00Z',
    image_url: null,
  },
]

export const MOCK_WORKLOG = [
  {
    id: '1',
    project_id: '1',
    date: '2025-07-31',
    weather: 'sunny',
    temp: 32,
    workers: 18,
    foremen: 2,
    work_done: 'יציקת תקרה קומה 3 — שטח 240 מ"ר. הושלמה יציקה בשעות 06:00-12:00. נדגמו 3 קוביות לבדיקת לחץ.',
    materials: 'בטון B30 — 48 מ"ק, ברזל ∅12 — 800 ק"ג',
    issues: 'עיכוב של שעה בגלל הגעה מאוחרת של משאיות המשאבה',
    inspector: 'חיים עזרא',
    created_at: '2025-07-31T18:00:00Z',
  },
  {
    id: '2',
    project_id: '1',
    date: '2025-07-30',
    weather: 'cloudy',
    temp: 28,
    workers: 22,
    foremen: 3,
    work_done: 'הנחת ברזל תקרה קומה 3 — 100% הושלם. מילוי חוליות בין קומות.',
    materials: 'ברזל ∅16 — 1.2 טון, עמודי פלדה — 12 יח\'',
    issues: 'ללא',
    inspector: 'חיים עזרא',
    created_at: '2025-07-30T17:30:00Z',
  },
  {
    id: '3',
    project_id: '1',
    date: '2025-07-29',
    weather: 'sunny',
    temp: 34,
    workers: 20,
    foremen: 2,
    work_done: 'קידום עבודות שלד קומה 3 — יציקת עמודים 8 יח\'. בדיקת רצף הברזל לפי תוכניות קונסטרוקציה.',
    materials: 'בטון B30 — 12 מ"ק, תבניות 180 מ"ר',
    issues: 'ללא',
    inspector: 'חיים עזרא',
    created_at: '2025-07-29T17:00:00Z',
  },
  {
    id: '4',
    project_id: '1',
    date: '2025-07-28',
    weather: 'sunny',
    temp: 31,
    workers: 15,
    foremen: 2,
    work_done: 'בנייה קומה 2 — קירות בלוקים חיצוניים 70%. הצבת מנופים.',
    materials: 'בלוקים 20 ס"מ — 1,200 יח\'',
    issues: 'ללא',
    inspector: 'חיים עזרא',
    created_at: '2025-07-28T17:30:00Z',
  },
]

export const MOCK_TASKS = [
  {
    id: '1',
    project_id: '1',
    title: 'בדיקת תוצאות קוביות בטון — יציקה 31.7',
    description: 'לקבל מהמעבדה תוצאות לחץ של 3 קוביות שנלקחו.',
    priority: 'high',
    status: 'todo',
    assignee: 'חיים עזרא',
    due_date: '2025-08-07',
    created_at: '2025-07-31T18:00:00Z',
  },
  {
    id: '2',
    project_id: '1',
    title: 'תיאום עם קבלן טיח לתיקון סדקים',
    description: 'לתאם עם קבלן הטיח ביקור לראיית הממצא #13 ולקבל הצעת לוז לתיקון.',
    priority: 'medium',
    status: 'in_progress',
    assignee: 'חיים עזרא',
    due_date: '2025-08-05',
    created_at: '2025-07-25T11:00:00Z',
  },
  {
    id: '3',
    project_id: '1',
    title: 'הגשת דוח ביניים לבעל הבית',
    description: 'להכין ולשלוח דוח חודשי על ממצאים פתוחים, לוח זמנים ותשלומים.',
    priority: 'high',
    status: 'todo',
    assignee: 'חיים עזרא',
    due_date: '2025-08-03',
    created_at: '2025-07-28T09:00:00Z',
  },
  {
    id: '4',
    project_id: '2',
    title: 'בדיקת אינסטלציה — גבעתיים',
    description: 'ביקור אתר לבדיקת מערכת הביוב לפני סגירת תקרות.',
    priority: 'high',
    status: 'todo',
    assignee: 'חיים עזרא',
    due_date: '2025-08-04',
    created_at: '2025-07-29T10:00:00Z',
  },
  {
    id: '5',
    project_id: '1',
    title: 'אישור בטיחות לעבודה בגובה',
    description: 'להשיג אישור ממנהל הבטיחות לפני הפעלת פיגומים קומה 4.',
    priority: 'medium',
    status: 'done',
    assignee: 'חיים עזרא',
    due_date: '2025-07-31',
    created_at: '2025-07-27T09:00:00Z',
  },
  {
    id: '6',
    project_id: '3',
    title: 'עדכון לוח זמנים — מרכז מסחרי',
    description: 'לעדכן לוח זמנים ראשי לאחר ההשהיה של 3 שבועות.',
    priority: 'low',
    status: 'in_progress',
    assignee: 'חיים עזרא',
    due_date: '2025-08-10',
    created_at: '2025-07-28T14:00:00Z',
  },
]
